#!/bin/bash

_asdf_install() {
  git clone -c advice.detachedHead=false -q https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.7.8
  echo 'source ~/.asdf/asdf.sh' > ~/.bashrc && . /root/.asdf/asdf.sh && asdf plugin add terraform
  echo '/bin/bash -c "source /root/.asdf/asdf.sh && asdf reshim && terraform $*"' > /bin/terraform
  chmod +x /bin/terraform
}

_asdf_install
